apiVersion: 1
datasources:
  - name: Loki
    type: loki
    uid: example-loki
    access: proxy
    url: http://loki:3100
    isDefault: true
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
  - name: Jaeger
    type: jaeger
    uid: example-jaeger
    access: proxy
    url: http://jaeger-all-in-one:16686

